// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:2220a8e423b100442a9d0bdd49c897b70e8ac90692750224d5da2eb93d34e320",
    "semanticFingerprint": "typebox-value-hash-v1:7e31a49d097c20e0",
    "defaultSettings": {
        "trigger": "#",
        "roots": [],
        "gitReposOnly": true,
        "includeDotFolders": false,
        "completionSuffix": " "
    }
} as const;

export default artifact;
