// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:0a7d2232d6e95a9fe78377dc8fb797d4b2ee87558bba2b99e9cd865590fc8595",
    "semanticFingerprint": "typebox-value-hash-v1:77fe1df24e5c5dff",
    "defaultSettings": {
        "trigger": "#",
        "roots": [],
        "gitReposOnly": true,
        "includeDotFolders": false,
        "completionSuffix": " "
    }
} as const;

export default artifact;
