// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:8673d5fd3bf9c8e2f5f67eec6cf88d019b83ee9bcdef62ec5053a81fa3838707",
    "semanticFingerprint": "typebox-value-hash-v1:4328a20854e0d369",
    "defaultSettings": {
        "trigger": "#",
        "roots": [],
        "gitReposOnly": true,
        "includeDotFolders": false,
        "completionSuffix": " ",
        "initialSuggestions": {
            "strategy": "frecency",
            "pinned": []
        }
    }
} as const;

export default artifact;
