// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:e49bc5b87534dcfe22963def0bf77df5d4fc8fa72b44b890c40df483a21d051e",
    "semanticFingerprint": "typebox-value-hash-v1:c11c7529da24ac23",
    "defaultSettings": {
        "trigger": "$",
        "hideSlashSkills": true,
        "completionSuffix": " "
    }
} as const;

export default artifact;
