// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:48873db52292023b975e3b474a341ef614942c39f4a9700bc55f08021e0643bb",
    "semanticFingerprint": "typebox-value-hash-v1:22594ba70fe7f6d8",
    "defaultSettings": {
        "trigger": "$",
        "hideSlashSkills": true,
        "completionSuffix": " "
    }
} as const;

export default artifact;
