// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:6068fb01eaa1b4e2e46d7bea643342bd95af1b52617b924f5b45e5bc0266821b",
    "semanticFingerprint": "typebox-value-hash-v1:3ad1f77c03289771",
    "defaultSettings": {
        "trigger": "$",
        "hideSlashSkills": true,
        "completionSuffix": " ",
        "initialSuggestions": {
            "strategy": "frecency",
            "pinned": [],
            "projectSkillsFirst": false
        }
    }
} as const;

export default artifact;
