// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:aa8a68aa1a90b13f73312a43f75fa7b7389976e68f20b270f9ae865f084c0a28",
    "semanticFingerprint": "typebox-value-hash-v1:34e4ab01629dbedc",
    "defaultSettings": {
        "urlColor": "#87d7ff"
    }
} as const;

export default artifact;
