// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:a24737e8381c21f2b8de044f69e3b461232008c1f920f6183ccbd05e73d58f66",
    "semanticFingerprint": "typebox-value-hash-v1:ba4b4bf7b208486c",
    "defaultSettings": {
        "enabled": true,
        "autocompleteAboveInput": true,
        "autoExpandPasteOnSubmit": true,
        "bashExecPromptSpacing": true,
        "anchorInputToBottom": false,
        "compactModelSelector": true,
        "editorMaxHeight": "unlimited",
        "hideAutocompleteScrollInfo": true,
        "hideModelChangeStatus": true,
        "hideModelProviderHint": true,
        "hideSlashCommandSourceTags": true,
        "highlightSelectedModelProvider": true,
        "inputPromptPrefix": "> ",
        "neutralBorderColor": true,
        "pasteClickToExpand": true,
        "pasteCollapseCharThreshold": 5000,
        "pasteCollapseEnabled": true,
        "pasteCollapseExpandKey": null,
        "pasteCollapseLineThreshold": 80,
        "pasteCollapseUseToolExpandKey": true,
        "pasteOffloadLineThreshold": 500,
        "pasteOffloadToDisk": false,
        "preserveCompactionHistory": false,
        "restoreContentAfterAutocompleteClose": true,
        "selectedOptionPrefix": "→ ",
        "showEditorOverflowIndicators": true
    }
} as const;

export default artifact;
