// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:a01e05a9004240c559697c59c32a15502ae4bd13066d9071a71af06c531ae93e",
    "semanticFingerprint": "typebox-value-hash-v1:bf0f398d591298ea",
    "defaultSettings": {
        "enabled": true,
        "autocompleteAboveInput": true,
        "bashExecPromptSpacing": true,
        "anchorInputToBottom": false,
        "compactModelSelector": true,
        "hideAutocompleteScrollInfo": true,
        "hideModelChangeStatus": true,
        "hideModelProviderHint": true,
        "hideSlashCommandSourceTags": true,
        "highlightSelectedModelProvider": true,
        "inputPromptPrefix": "> ",
        "neutralBorderColor": true,
        "pasteCollapseCharThreshold": 1000,
        "pasteCollapseEnabled": true,
        "pasteCollapseExpandKey": null,
        "pasteCollapseLineThreshold": 10,
        "pasteCollapseUseToolExpandKey": true,
        "preserveCompactionHistory": false,
        "restoreContentAfterAutocompleteClose": true,
        "refreshTmuxHyperlinks": true,
        "selectedOptionPrefix": "→ "
    }
} as const;

export default artifact;
