// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:71ffe910659edb15d90501b3671378a0deda3426620724eebc15fa34dcfba874",
    "semanticFingerprint": "typebox-value-hash-v1:02655cb4562804d5",
    "defaultSettings": {
        "enabled": true,
        "autocompleteAboveInput": true,
        "bashExecPromptSpacing": true,
        "anchorInputToBottom": false,
        "compactModelSelector": true,
        "hideAutocompleteScrollInfo": true,
        "hideModelChangeStatus": true,
        "hideModelProviderHint": true,
        "hideSlashCommandSourceTags": true,
        "highlightSelectedModelProvider": true,
        "inputPromptPrefix": "> ",
        "neutralBorderColor": true,
        "pasteCollapseCharThreshold": 1000,
        "pasteCollapseEnabled": true,
        "pasteCollapseExpandKey": null,
        "pasteCollapseLineThreshold": 10,
        "pasteCollapseUseToolExpandKey": true,
        "preserveCompactionHistory": false,
        "restoreContentAfterAutocompleteClose": true,
        "selectedOptionPrefix": "→ "
    }
} as const;

export default artifact;
