// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:6e12e167c662f9159e875d8508449ffc5a598ce2c4004460f26c2dfc8c4d31d9",
    "semanticFingerprint": "typebox-value-hash-v1:7e6416f4ef5a1478",
    "defaultSettings": {
        "include": [],
        "exclude": []
    },
    "exampleSettings": {
        "include": [
            {
                "provider": "openai-codex",
                "models": [
                    "gpt-5.*"
                ]
            }
        ],
        "exclude": [
            {
                "provider": "openai-codex",
                "models": [
                    "*-mini"
                ]
            }
        ]
    }
} as const;

export default artifact;
