// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:5478a633cb428026ed5f26103eaa6d4b1b285aa1600b10cceefc81b22004abbe",
    "semanticFingerprint": "typebox-value-hash-v1:d3dd102d16efaa1c",
    "defaultSettings": {
        "version": 1,
        "currentMode": "default",
        "modeUseThinkingBorderColors": false,
        "modeShowThinkingLevelStatus": false,
        "modes": {}
    },
    "exampleSettings": {
        "currentMode": "deep",
        "modes": {
            "fast": {
                "provider": "openai-codex",
                "modelId": "gpt-5.4-mini",
                "thinkingLevel": "low",
                "color": "thinkingLow"
            },
            "deep": {
                "provider": "openai-codex",
                "modelId": "gpt-5.6-sol",
                "thinkingLevel": "high",
                "color": "thinkingHigh"
            }
        }
    }
} as const;

export default artifact;
