// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:7c6cf2cf57e7c1b4ac2c05b86b6d4c6d621ccaa5e14439a4115c0c5c513d80d6",
    "semanticFingerprint": "typebox-value-hash-v1:4bc8364b713427b7",
    "defaultSettings": {
        "treeTimestampMode": "relative",
        "treeSelectedPreview": false,
        "treePreviewFullHeight": true
    }
} as const;

export default artifact;
