// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:fa280cd3945d961f0a53981de81bb14aa8d999a1843d982dfd47fcad607b7e38",
    "semanticFingerprint": "typebox-value-hash-v1:aa3744846194d2a0",
    "defaultSettings": {
        "separator": "·",
        "showGitAheadBehind": false,
        "layout": {
            "left": [
                "path",
                "branch",
                "provider",
                "model",
                "thinking"
            ],
            "right": [
                "context"
            ],
            "hidden": []
        }
    }
} as const;

export default artifact;
