// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:d5bfd7245374bdb415f9539e00ba99707eb0da9ea5bc5d9c5766e4520be25352",
    "semanticFingerprint": "typebox-value-hash-v1:8d1a6e4330cef2fc",
    "defaultSettings": {
        "aliases": [],
        "providerAliases": [],
        "stableProviderColumn": true
    },
    "exampleSettings": {
        "aliases": [
            {
                "provider": "anthropic",
                "model": "claude-sonnet-4-5",
                "alias": "sonnet",
                "name": "Claude Sonnet 4.5"
            },
            {
                "provider": "openai-codex",
                "model": "gpt-5.6-sol",
                "alias": "sol"
            }
        ],
        "providerAliases": [
            {
                "provider": "openai-codex",
                "name": "Codex"
            }
        ]
    }
} as const;

export default artifact;
