// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:92da3e1bf772840f7468861d0254bbb5c426ffa2978c9ca1d4bd0eaf9b673b90",
    "semanticFingerprint": "typebox-value-hash-v1:865a985b05b2e33f",
    "defaultSettings": {
        "statusBar": {
            "active": {
                "timer": {
                    "visible": true,
                    "paused": false
                }
            },
            "idle": {
                "visible": true,
                "showLastRunSummary": true
            }
        },
        "rightMessages": {
            "enabled": false,
            "intervalMs": 10000,
            "minGap": 4,
            "minScrollCycles": 1,
            "scrollColumnIntervalMs": 120,
            "dimmed": true,
            "italic": true,
            "messages": []
        }
    }
} as const;

export default artifact;
