// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:f2c3d80aaa94a1ecd76decf264ce0eeaa86c59f8bb5f205cb4acadcb84ad2781",
    "semanticFingerprint": "typebox-value-hash-v1:a4e5131dc4a70f49",
    "defaultSettings": {
        "statusBar": {
            "active": {
                "timer": {
                    "visible": true,
                    "paused": false
                }
            },
            "idle": {
                "visible": true,
                "showLastRunSummary": true,
                "showTokensPerSecond": true
            }
        },
        "rightMessages": {
            "enabled": false,
            "intervalMs": 10000,
            "minGap": 4,
            "minScrollCycles": 1,
            "scrollColumnIntervalMs": 120,
            "dimmed": true,
            "italic": true,
            "messages": []
        }
    }
} as const;

export default artifact;
